from distutils.command.upload import upload
from itertools import count
from sys import displayhook
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    campaign=models.CharField(max_length=100,null=True,blank=True)
    user_level=models.IntegerField(null=True,blank=True)
    status=models.CharField(max_length=25,null=True,blank=True)
    usergroup=models.CharField(max_length=25,null=True,blank=True)

class Dataupload(models.Model):
    campion=models.CharField(max_length=100,null=True,blank=True)
    listid=models.CharField(max_length=100,null=True,blank=True,unique=True)
    listname=models.CharField(max_length=100,null=True,blank=True)
    file=models.FileField(null=True)
    count = models.BigIntegerField(null=True,blank=True)
    entry=models.DateTimeField(null=True,blank=True)
    status=models.IntegerField(null=True,blank=True,default=1)

class personaldetails(models.Model):
    borrowor_name=models.CharField(max_length=100,null=True,blank=True)
    mobile_number=models.CharField(max_length=100,null=True,blank=True)
    address=models.TextField(null=True,blank=True)
    state=models.CharField(max_length=300,null=True,blank=True)
    pincode=models.CharField(max_length=300,null=True,blank=True)
    dateofbirth=models.DateField(null=True,blank=True)
    email_id=models.EmailField(null=True,blank=True)
    phone_number=models.CharField(max_length=100,null=True,blank=True)

    bankname=models.CharField(max_length=100,null=True,blank=True)
    trustname=models.CharField(max_length=100,null=True,blank=True)
    systemlan=models.CharField(max_length=100,null=True,blank=True)
    bank_loan_accountno=models.CharField(max_length=100,null=True,blank=True)
    branchname=models.CharField(max_length=100,null=True,blank=True)
    bankstate=models.CharField(max_length=100,null=True,blank=True)
    nature_of_facility=models.CharField(max_length=100,null=True,blank=True)
    sanctionamount=models.BigIntegerField(null=True,blank=True)
    loan_sanction_date=models.DateField(null=True,blank=True)
    NPA_Date=models.DateField(null=True,blank=True)
    interest_rate=models.CharField(max_length=100,null=True,blank=True)
    account_status=models.CharField(max_length=100,null=True,blank=True)
    security_value=models.CharField(max_length=100,null=True,blank=True)
    document_custody=models.CharField(max_length=100,null=True,blank=True)
    security_flag=models.CharField(max_length=100,null=True,blank=True)
    current_allocation=models.CharField(max_length=100,null=True,blank=True)
    current_allocation_date=models.DateField(null=True,blank=True)
    team_leader=models.CharField(max_length=100,null=True,blank=True)
    zone_name=models.CharField(max_length=100,null=True,blank=True)
    branch_mail_id=models.EmailField(null=True,blank=True)
    branch_contact_details=models.CharField(max_length=100,null=True,blank=True)
    total_collected_amount=models.BigIntegerField(null=True,blank=True)
    balance_POS_amount=models.BigIntegerField(null=True,blank=True)
    TOS=models.BigIntegerField(null=True,blank=True)
    TOS_as_on_Date=models.DateField(null=True,blank=True)
    next_action_date=models.DateField(null=True,blank=True)
    current_principal_outstanding=models.BigIntegerField(null=True,blank=True)
   
    payment_date=models.DateField(null=True,blank=True)
    agent_username=models.CharField(max_length=100,null=True,blank=True)
    city=models.CharField(max_length=100,null=True,blank=True)
    disposition=models.CharField(max_length=100,null=True,blank=True)
    sub_dispossitions=models.CharField(max_length=100,null=True,blank=True)
    mode=models.CharField(max_length=100,null=True,blank=True)
    transactionid_chequeno=models.CharField(max_length=100,null=True,blank=True)
    cash=models.BigIntegerField(null=True,blank=True)
    schedule=models.DateTimeField(null=True,blank=True)
    field_branch=models.CharField(max_length=1,null=True,blank=True)
    datetime=models.DateTimeField(null=True,blank=True)
    callbacktime=models.DateTimeField(null=True,blank=True)
    amount=models.BigIntegerField(null=True,blank=True)
    remark=models.CharField(max_length=100,null=True,blank=True)
    contacted_DateTime=models.DateTimeField(max_length=100,null=True,blank=True)
    created_by = models.CharField(max_length=100,null=True,blank=True)
    caller_name=models.CharField(max_length=200,null=True,blank=True)
    loanamt=models.BigIntegerField(null=True,blank=True)
    lastdial=models.CharField(max_length=15,null=True,blank=True)
    user_id = models.IntegerField(null=True,blank=True)
    
    callername = models.CharField(max_length=250,null=True,blank=True)
    attempted = models.BigIntegerField(default=0)
    what=models.CharField(max_length=15,null=True,blank=True)
    alt_mno_1 =  models.CharField(max_length=25,null=True,blank=True)
    alt_mno_2 =  models.CharField(max_length=25,null=True,blank=True)
    alt_mno_3 =  models.CharField(max_length=25,null=True,blank=True)
    list_id=models.ForeignKey(Dataupload,on_delete=models.CASCADE,null=True)
    additional_number = models.CharField(max_length=25,null=True,blank=True)
    additional_address = models.TextField(null=True,blank=True)
    additional_emailid = models.CharField(max_length=100,null=True,blank=True)



class user_group(models.Model):
    usergroup=models.CharField(max_length=200,null=True,blank=True)
    allowed_campaigns=models.CharField(max_length=200,null=True,blank=True)

class Additional(models.Model):
    debtor_id=models.ForeignKey(personaldetails,on_delete=models.CASCADE)
    email=models.EmailField(null=True,blank=True)
    contactnum=models.CharField(max_length=20,null=True,blank=True)
    relation=models.CharField(max_length=200,null=True,blank=True)
    address=models.CharField(max_length=200,null=True,blank=True)
    state=models.CharField(max_length=200,null=True,blank=True)
    city=models.CharField(max_length=200,null=True,blank=True)
    landmark=models.CharField(max_length=200,null=True,blank=True)
    pincode=models.CharField(max_length=20,null=True,blank=True)
    
    user_id = models.IntegerField(null=True,blank=True)
    
# DATE_INPUT_FORMATS = ['%d-%m-%Y']
class otsdata(models.Model):
    info=models.ForeignKey(personaldetails,on_delete=models.CASCADE)
    borrower_name=models.CharField(max_length=100,null=True,blank=True)
    loan_id=models.CharField(max_length=100,null=True,blank=True)
    ots_amt=models.BigIntegerField(null=True,blank=True)
    tos=models.CharField(max_length=100,null=True,blank=True)
    ots=models.CharField(max_length=100,null=True,blank=True)
    otspercentage=models.CharField(max_length=100,null=True,blank=True)
    tlstat=models.CharField(max_length=100,null=True,blank=True)
    tlstatdate=models.DateField(null=True,blank=True)
    suggest=models.CharField(max_length=100,null=True,blank=True)
    remark=models.CharField(max_length=100,null=True,blank=True)
    callername = models.CharField(max_length=20,null=True,blank=True)



class emi(models.Model):
    refrence=models.ForeignKey(personaldetails,on_delete=models.CASCADE)
    emi=models.CharField(max_length=100,null=True,blank=True)
    emidate1=models.DateField(null=True,blank=True)
    amount1=models.BigIntegerField(null=True,blank=True)
    emidate2=models.DateField(null=True,blank=True)
    amount2=models.BigIntegerField(null=True,blank=True)
    emidate3=models.DateField(null=True,blank=True)
    amount3=models.BigIntegerField(null=True,blank=True)
    emidate4=models.DateField(null=True,blank=True)
    amount4=models.BigIntegerField(null=True,blank=True)
    remarks=models.CharField(max_length=100,null=True,blank=True)
    user_id = models.IntegerField(null=True,blank=True)


class sendfeto(models.Model):
    client=models.ForeignKey(personaldetails,on_delete=models.CASCADE)
    address=models.CharField(max_length=100,null=True,blank=True)
    area=models.CharField(max_length=100,null=True,blank=True)
    landmark=models.CharField(max_length=100,null=True,blank=True)
    pincode=models.CharField(max_length=100,null=True,blank=True)
    fe_datetime=models.DateTimeField(null=True,blank=True)
    amount=models.BigIntegerField(null=True,blank=True)
    modeofpay=models.CharField(max_length=100,null=True,blank=True)
    agentname=models.CharField(max_length=100,null=True,blank=True)
    user_id = models.IntegerField(null=True,blank=True)
    contacted_datetime=models.DateTimeField(null=True,blank=True)

    


class Excelformat(models.Model):
    dataformat = models.FileField(null=True)
    created = models.DateField(auto_now_add=True,null=True)

class campaign(models.Model):
    campaign_id = models.CharField(max_length=200,null=True,blank=True)
    campaign_name = models.CharField(max_length=200,null=True,blank=True)
    camp_group=models.CharField(max_length=200,null=True,blank=True)

class LogData(models.Model):
    borrowor_name=models.CharField(max_length=100,null=True,blank=True)
    mobile_number=models.CharField(max_length=100,null=True,blank=True)
    address=models.CharField(max_length=300,null=True,blank=True)
    state=models.CharField(max_length=300,null=True,blank=True)
    pincode=models.CharField(max_length=300,null=True,blank=True)
    dateofbirth=models.DateField(null=True,blank=True)
    email_id=models.EmailField(null=True,blank=True)
    phone_number=models.CharField(max_length=100,null=True,blank=True)
    bankname=models.CharField(max_length=100,null=True,blank=True)
    trustname=models.CharField(max_length=100,null=True,blank=True)
    systemlan=models.CharField(max_length=100,null=True,blank=True)
    bank_loan_accountno=models.CharField(max_length=100,null=True,blank=True)
    branchname=models.CharField(max_length=100,null=True,blank=True)
    bankstate=models.CharField(max_length=100,null=True,blank=True)
    nature_of_facility=models.CharField(max_length=100,null=True,blank=True)
    sanctionamount=models.BigIntegerField(null=True,blank=True)
    loan_sanction_date=models.DateField(null=True,blank=True)
    NPA_Date=models.DateField(null=True,blank=True)
    interest_rate=models.CharField(max_length=100,null=True,blank=True)
    account_status=models.CharField(max_length=100,null=True,blank=True)
    security_value=models.CharField(max_length=100,null=True,blank=True)
    document_custody=models.CharField(max_length=100,null=True,blank=True)
    security_flag=models.CharField(max_length=100,null=True,blank=True)
    current_allocation=models.CharField(max_length=100,null=True,blank=True)
    current_allocation_date=models.DateField(null=True,blank=True)
    team_leader=models.CharField(max_length=100,null=True,blank=True)
    zone_name=models.CharField(max_length=100,null=True,blank=True)
    branch_mail_id=models.EmailField(null=True,blank=True)
    branch_contact_details=models.CharField(max_length=100,null=True,blank=True)
    total_collected_amount=models.BigIntegerField(null=True,blank=True)
    balance_POS_amount=models.BigIntegerField(null=True,blank=True)
    TOS=models.BigIntegerField(null=True,blank=True)
    TOS_as_on_Date=models.DateField(null=True,blank=True)
    next_action_date=models.DateField(null=True,blank=True)
    current_principal_outstanding=models.BigIntegerField(null=True,blank=True) 
    payment_date=models.DateField(null=True,blank=True)
    agent_username=models.CharField(max_length=100,null=True,blank=True)
    city=models.CharField(max_length=100,null=True,blank=True)
    disposition=models.CharField(max_length=100,null=True,blank=True)
    sub_dispossitions=models.CharField(max_length=100,null=True,blank=True)
    mode=models.CharField(max_length=100,null=True,blank=True)
    transactionid_chequeno=models.CharField(max_length=100,null=True,blank=True)
    cash=models.BigIntegerField(null=True,blank=True)
    schedule=models.DateTimeField(null=True,blank=True)
    field_branch=models.CharField(max_length=1,null=True,blank=True)
    datetime=models.DateTimeField(null=True,blank=True)
    callbacktime=models.DateTimeField(null=True,blank=True)
    amount=models.BigIntegerField(null=True,blank=True)
    remark=models.CharField(max_length=100,null=True,blank=True)
    contacted_DateTime=models.DateTimeField(max_length=100,null=True,blank=True)
    created_by = models.CharField(max_length=100,null=True,blank=True)
    caller_name=models.CharField(max_length=200,null=True,blank=True)
    loanamt=models.BigIntegerField(null=True,blank=True)
    lastdial=models.CharField(max_length=15,null=True,blank=True)

    # ots
    ots_amt=models.BigIntegerField(null=True,blank=True)
    ots_tos=models.CharField(max_length=100,null=True,blank=True)
    otspercentage=models.CharField(max_length=100,null=True,blank=True)
    tlstat=models.CharField(max_length=100,null=True,blank=True)
    tlstatdate=models.DateField(null=True,blank=True)
    suggest=models.CharField(max_length=100,null=True,blank=True)
    otsremark=models.CharField(max_length=100,null=True,blank=True)

    # emi
    emi=models.CharField(max_length=100,null=True,blank=True)
    emidate1=models.DateField(null=True,blank=True)
    amount1=models.BigIntegerField(null=True,blank=True)
    emidate2=models.DateField(null=True,blank=True)
    amount2=models.BigIntegerField(null=True,blank=True)
    emidate3=models.DateField(null=True,blank=True)
    amount3=models.BigIntegerField(null=True,blank=True)
    emidate4=models.DateField(null=True,blank=True)
    amount4=models.BigIntegerField(null=True,blank=True)
    emiremark=models.CharField(max_length=100,null=True,blank=True)

    # sendfeto
    fe_address=models.CharField(max_length=100,null=True,blank=True)
    fe_area=models.CharField(max_length=100,null=True,blank=True)
    fe_landmark=models.CharField(max_length=100,null=True,blank=True)
    fe_pincode=models.CharField(max_length=100,null=True,blank=True)
    fe_datetime=models.DateTimeField(null=True,blank=True)
    amount=models.BigIntegerField(null=True,blank=True)
    modeofpay=models.CharField(max_length=100,null=True,blank=True)
    campaign=models.CharField(max_length=100,null=True,blank=True)

    personalForkey=models.ForeignKey(personaldetails,on_delete=models.CASCADE,null=True)
    
    alt_mno_1 =  models.CharField(max_length=25,null=True,blank=True)
    alt_mno_2 =  models.CharField(max_length=25,null=True,blank=True)
    alt_mno_3 =  models.CharField(max_length=25,null=True,blank=True)
    list_id=models.BigIntegerField(null=True,blank=True)
    additional_number = models.CharField(max_length=25,null=True,blank=True)
    additional_address = models.TextField(null=True,blank=True)
    additional_emailid = models.CharField(max_length=25,null=True,blank=True)
    paidptpcount=models.BigIntegerField(default=0)

class IncomingDetails(models.Model):
    name=models.CharField(max_length=100,null=True,blank=True)
    mobile=models.CharField(max_length=100,null=True,blank=True)
    accountno=models.CharField(max_length=100,null=True,blank=True)
    disposition=models.CharField(max_length=100,null=True,blank=True)
    sub_disposition=models.CharField(max_length=100,null=True,blank=True)
    remark=models.CharField(max_length=100,null=True,blank=True)

class SMSUpload(models.Model):
    upload_by=models.CharField(max_length=100,null=True,blank=True)
    smsid=models.CharField(max_length=100,null=True,blank=True,unique=True)
    smstype=models.CharField(max_length=100,null=True,blank=True)
    file=models.FileField(null=True)
    count = models.BigIntegerField(null=True,blank=True)
    entry=models.DateTimeField(null=True,blank=True)
    sent=models.CharField(max_length=100,null=True,blank=True)

class SMSDetails(models.Model):
    phone_no=models.CharField(max_length=100,null=True,blank=True)
    Date=models.DateField(null=True,blank=True)
    loan_account_no=models.CharField(max_length=100,null=True,blank=True,)
    amount=models.CharField(max_length=100,null=True,blank=True)
    agency_name=models.CharField(max_length=100,null=True,blank=True)
    response=models.CharField(max_length=100,null=True,blank=True)
    smsty=models.CharField(max_length=100,null=True,blank=True)
    sms=models.CharField(max_length=1000,null=True,blank=True)
    entry=models.DateField(null=True,blank=True)
    created_by=models.ForeignKey(SMSUpload,on_delete=models.CASCADE,null=True)

class Score(models.Model):
    agent=models.CharField(max_length=100,null=True,blank=True)
    camp=models.CharField(max_length=100,null=True,blank=True)
    dispo=models.CharField(max_length=100,null=True,blank=True)
    contactdate=models.CharField(max_length=100,null=True,blank=True)
    aud=models.FileField(null=True)
    recordingid=models.BigIntegerField(null=True,blank=True)
    lastupdate=models.DateField(null=True,blank=True)
    marks1=models.BigIntegerField(null=True,blank=True)
    getmark1=models.BigIntegerField(null=True,blank=True)
    marks2=models.BigIntegerField(null=True,blank=True)
    getmark2=models.BigIntegerField(null=True,blank=True)
    marks3=models.BigIntegerField(null=True,blank=True)
    getmark3=models.BigIntegerField(null=True,blank=True)
    marks4=models.BigIntegerField(null=True,blank=True)
    getmark4=models.BigIntegerField(null=True,blank=True)
    marks5=models.BigIntegerField(null=True,blank=True)
    getmark5=models.BigIntegerField(null=True,blank=True)
    marks6=models.BigIntegerField(null=True,blank=True)
    getmark6=models.BigIntegerField(null=True,blank=True)
    marks7=models.BigIntegerField(null=True,blank=True)
    getmark7=models.BigIntegerField(null=True,blank=True)
    marks8=models.BigIntegerField(null=True,blank=True)
    getmark8=models.BigIntegerField(null=True,blank=True)
    marks9=models.BigIntegerField(null=True,blank=True)
    getmark9=models.BigIntegerField(null=True,blank=True)
    total=models.BigIntegerField(null=True,blank=True)
    got=models.BigIntegerField(null=True,blank=True)
    performance=models.CharField(max_length=100,null=True,blank=True)
    userForKey=models.ForeignKey(User,on_delete=models.CASCADE,null=True)


class LoginHistory(models.Model):
    username=models.CharField(max_length=100,null=True,blank=True)
    logdt=models.DateTimeField(null=True,blank=True)
    event = models.CharField(max_length=100,null=True,blank=True)


class MissedCall(models.Model):
    username=models.CharField(max_length=100,null=True,blank=True)
    callnum=models.BigIntegerField(null=True,blank=True)
    missdt=models.DateTimeField(null=True,blank=True)
    callcount=models.BigIntegerField(null=True,blank=True)
    contacted=models.CharField(max_length=100,null=True,blank=True)
    name=models.CharField(max_length=100,null=True,blank=True)
    lan=models.CharField(max_length=100,null=True,blank=True)
    dispo=models.CharField(max_length=100,null=True,blank=True)
    sub_dispo=models.CharField(max_length=100,null=True,blank=True)
    remark=models.CharField(max_length=100,null=True,blank=True)
    cont_dt=models.DateTimeField(null=True,blank=True)
    