# Generated by Django 4.0.5 on 2022-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_group_user_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
