# Generated by Django 4.0.5 on 2022-08-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_personaldetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
