# Generated by Django 4.0.5 on 2022-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_smsupload_smsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsupload',
            name='sent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
