# Generated by Django 4.0.5 on 2022-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_smsupload_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
