# Generated by Django 4.0.5 on 2022-09-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_logdata_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='list_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dataupload'),
        ),
    ]
