# Generated by Django 4.0.5 on 2022-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_logdata_list_id_personaldetails_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsdetails',
            name='entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsupload',
            name='entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
