# Generated by Django 4.0.5 on 2022-09-29 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_dataupload_entry_alter_smsdetails_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('callnum', models.BigIntegerField(blank=True, null=True)),
                ('missdt', models.DateTimeField(blank=True, null=True)),
                ('callcount', models.BigIntegerField(blank=True, null=True)),
                ('contacted', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lan', models.CharField(blank=True, max_length=100, null=True)),
                ('dispo', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_dispo', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('cont_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='fe_date',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='time',
        ),
        migrations.RemoveField(
            model_name='sendfeto',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sendfeto',
            name='time',
        ),
        migrations.AddField(
            model_name='dataupload',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='fe_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='paidptpcount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sendfeto',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsupload',
            name='upload_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smsdetails',
            name='entry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
                ('camp', models.CharField(blank=True, max_length=100, null=True)),
                ('dispo', models.CharField(blank=True, max_length=100, null=True)),
                ('contactdate', models.CharField(blank=True, max_length=100, null=True)),
                ('aud', models.FileField(null=True, upload_to='')),
                ('recordingid', models.BigIntegerField(blank=True, null=True)),
                ('lastupdate', models.DateField(blank=True, null=True)),
                ('marks1', models.BigIntegerField(blank=True, null=True)),
                ('getmark1', models.BigIntegerField(blank=True, null=True)),
                ('marks2', models.BigIntegerField(blank=True, null=True)),
                ('getmark2', models.BigIntegerField(blank=True, null=True)),
                ('marks3', models.BigIntegerField(blank=True, null=True)),
                ('getmark3', models.BigIntegerField(blank=True, null=True)),
                ('marks4', models.BigIntegerField(blank=True, null=True)),
                ('getmark4', models.BigIntegerField(blank=True, null=True)),
                ('marks5', models.BigIntegerField(blank=True, null=True)),
                ('getmark5', models.BigIntegerField(blank=True, null=True)),
                ('marks6', models.BigIntegerField(blank=True, null=True)),
                ('getmark6', models.BigIntegerField(blank=True, null=True)),
                ('marks7', models.BigIntegerField(blank=True, null=True)),
                ('getmark7', models.BigIntegerField(blank=True, null=True)),
                ('marks8', models.BigIntegerField(blank=True, null=True)),
                ('getmark8', models.BigIntegerField(blank=True, null=True)),
                ('marks9', models.BigIntegerField(blank=True, null=True)),
                ('getmark9', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('got', models.BigIntegerField(blank=True, null=True)),
                ('performance', models.CharField(blank=True, max_length=100, null=True)),
                ('userForKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
