# Generated by Django 4.0.4 on 2022-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_sendfeto_contacted_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginhistory',
            old_name='campaign',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='count',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='logdata',
            name='additional_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='additional_emailid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='additional_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='logdt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='additional_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='additional_emailid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='additional_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
